# Autoprefix your CSS for browser compatibility
BROWSERS:
  - "Chrome >= 35"
  - "Firefox >= 31"
  - "Edge >= 12"
  - "Explorer >= 9"
  - "iOS >= 8"
  - "Safari >= 8"
  - "Android 2.3"
  - "Android >= 4"
  - "Opera >= 12"

# The name of your .css and .js files
FILENAME: "app"

# Include temp/holder.min.js in the output directory for placeholder images
INCLUDE_HOLDER: true

# Your project's paths
PATHS:
  #Local web server root path, output from 'npm start', e.g. "_site"
  site: "dist" 
  #The build path, output from 'npm run build'
  build: "dist"
  #Javascript, optimize .js size by commenting out unused scripts
  js:
    #JQuery
    - "node_modules/jquery/dist/jquery.min.js"
    #Bootstrap
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/affix.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/alert.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/button.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/carousel.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/collapse.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/modal.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/tab.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/transition.js"
    - "node_modules/bootstrap-sass/assets/javascripts/bootstrap/popover.js"

# The port your project's local web server will use, e.g. 8080
PORT: 8080

# Sass configurations, includePaths has "node_modules/" to find Bootstrap 
SASS_OPTIONS:
  errLogToConsole: true
  outputStyle: "expanded"
  includePaths: "node_modules/"
